### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by kochd** [danielpclark/elixirize#1]
Cant we just do:
```
s = "a b c d"
val = s.
      split(" ").
      join("-").
      capitalize
val
```

? This works with native ruby.

**Comment by danielpclark** [comment]
The README says why right after that example.  It's an option available for anyone who'd like to maintain consistency in style and provide a visual reminder to re-implement the design should they want to _(into a pipe forward code base)_.  The `~` method on Symbol is an extra for the reasons stated above.

You don't need to change the way you write your code, it's completely up to you.

That's not the main feature — that's an extra.

**Comment by danielpclark** [comment]
Some of the people that specific function may help are those who want to refactor to "Tell Don't Ask" and ["Eastward Oriented Code"](https://www.youtube.com/watch?v=kXcrClJcfm8).

It's a TODO flag for decoupling knowledge about other objects which don't belong in the current scope.
