### ISSUE TITLE
Call class method

### ISSUE THREAD

**Issue by sphynx79** [danielpclark/elixirize#2]
Please can you tell how i call call class method
``` ruby
file = "./excel_file/download//remit_2017_09_01.xlsx"
d    = file.
       ᐅ(~:split, '/').
       ᐅ(~:last).
       ᐅ(~:gsub, /remit_|.xlsx/i, "").
       ᐅ(~:"DateTime.strptime", "%Y_%m_%d")

```

return :
error: undefined method `DateTime.strptime' for "2017_09_01":String

And this work:
``` ruby
file               = "./excel_file/download//remit_2017_09_01.xlsx"
to_datetime =  ->(string) { DateTime.strptime(string,"%Y_%m_%d") }
d = @file.
       ᐅ(~:split, '/').
       ᐅ(~:last).
       ᐅ(~:gsub, /remit_|.xlsx/i, "").
       ᐅ to_datetime
```

Thanks

**Comment by jesse-c** [comment]
I'm curious about this too, and also when it's in a module—e.g. `Foo::Bar.new`.

**Comment by danielpclark** [comment]
In those cases you should directly call the `method` method on the object and pass the method to it you wish to act as a Proc.

So your:

```ruby
ᐅ(~:"DateTime.strptime", "%Y_%m_%d")
```

Should be:

```ruby
ᐅ(DateTime.method(:strptime), "%Y_%m_%d")
```

And @jesse-c your example would be:

```ruby
ᐅ(Foo::Bar.method(:new), *args)
```

**Comment by danielpclark** [comment]
The tilde method `~` on `Symbol` is a helper method which simply calls `to_proc` on the symbol.  This creates a Proc that will call that symbol as a method on whatever object you hand it.  The `ᐅ` method simply passes `self` as the first argument to whatever Proc you hand it as it's first parameter.

* `A ᐅ B` is the same as `B.call(A)` with arguments/parameters if provided
* `~:b` is the same as `:b.to_proc` which makes a Proc like `->input, *args{ input.send(:b, *args)}`

Ruby's `method` method can take any method on any object and create a `call` method so the method can be used as a Proc which is what ᐅ expects as its first parameter.

**Comment by jesse-c** [comment]
@danielpclark thank you for the detailed explanation! That makes a lot more sense. 

This is now my inexperience with Ruby showing, but have you seen an error like this before? `in 'read': no implicit conversion of Proc into String (TypeError)`

Full stacktrace:
```
/../brewer.rb:21:in `read': no implicit conversion of Proc into String (TypeError)
	from /../brewer.rb:21:in `block (2 levels) in initialize'
	from /Library/Ruby/Gems/2.3.0/gems/elixirize-0.5.0/lib/elixirize.rb:7:in `ᐅ'
	from /../brewer.rb:20:in `block in initialize'
	from /../brewer.rb:18:in `each'
	from /../brewer.rb:18:in `each_with_object'
	from /../brewer.rb:18:in `initialize'
	from ../brewer.rb:15:in `new'
	from ../brewer.rb:15:in `<main>'
```

Code snippet:
```
    @brewfiles = @filenames.each_with_object({}) do |v,h| 
      h[v] = File.join(path, v).
              ᐅ->(f) { File.expand_path f }.
              ᐅ->(f) { File.read f }
              ᐅBundle::Dsl.method(:new)
    end
```

It works all the way up to the [`Bundle::Dsl.new`](https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/dsl.rb#L15) call. In my dumb-debugging, I tried a few different versions such as `ᐅ(Bundle::Dsl.method(:new))` and `ᐅ(Bundle::Dsl.method(:new), nil)`,

**Comment by danielpclark** [comment]
Could you try something like:

```ruby
@brewfiles = @filenames.each_with_object({}) do |v,h| 
  h[v] = path.
    ᐅ( File.method(:join), v     ).
    ᐅ( File.method(:expand_path) ).
    ᐅ( File.method(:read)        ).
    ᐅ  Bundle::Dsl.method(:new)
end
```

Also you're missing a period after `ᐅ->(f) { File.read f }` and I don't see where you're getting path from.

If `path` is a Pathname object you can simplify it.

```ruby
require 'pathname'

path = Pathname.new(path)

@brewfiles = @filenames.each_with_object({}) do |v,h| 
  h[v] = path.
    ᐅ( ~:join, v     ).
    ᐅ( ~:expand_path ).
    ᐅ( ~:read        ).
    ᐅ  Bundle::Dsl.method(:new)
end
```

Keep in mind that the `Dsl.new` method must accept the previous result as it's first input.

**Comment by jesse-c** [comment]
The second one worked! Switching to using the `Pathname` type was a good idea. The first one too makes sense—and is a lot cleaner.

`path` was being defined earlier in the function and was used to get a list of files from that directory.
